# config/bigquery_config.yaml

default:
  dataset_id: "test_dataset"
  table_id: "Default_table1_id"
  schema: 
    - name: name
      field_type: STRING
      mode: REQUIRED
    - name: age
      field_type: INTEGER
      mode: REQUIRED
    - name: email
      field_type: STRING
      mode: REQUIRED

tables:
  users:
    dataset_id: "test_dataset"
    table_id: "users"
    schema:
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: age
        field_type: INTEGER
        mode: REQUIRED
      - name: email
        field_type: STRING
        mode: REQUIRED

  products:
    dataset_id: "test_dataset"
    table_id: "products"
    schema:
      - name: product_id
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: age
        field_type: INTEGER
        mode: REQUIRED
      - name: email
        field_type: STRING
        mode: REQUIRED
      
