# config/bigquery_config.yaml

default:
  dataset_id: "test_dataset"
  table_id: "default_table"
  schema:
    - name: name
      field_type: STRING
      mode: REQUIRED
    - name: age
      field_type: INTEGER
      mode: REQUIRED
    - name: email
      field_type: STRING
      mode: REQUIRED

tables:
  users:
    dataset_id: "test_dataset"
    table_id: "users_table"
    schema:
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: age
        field_type: INTEGER
        mode: REQUIRED
      - name: email
        field_type: STRING
        mode: REQUIRED

  products:
    dataset_id: "test_dataset"
    table_id: "products_table"
    schema:
      - name: product_id
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: price
        field_type: FLOAT
        mode: REQUIRED
      - name: in_stock
        field_type: BOOLEAN
        mode: NULLABLE
